{{- include "ffc-helm-library.container-config-map" (list . "ffc-doc-statement-receiver.config-map") -}}
{{- define "ffc-doc-statement-receiver.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  ALERT_TOPIC_ADDRESS: {{ .Values.container.alertTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  ALERT_TOPIC_ADDRESS: {{ .Values.container.alertTopicAddress }}
  {{- end }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  AZURE_STORAGE_CONTAINER: {{ quote .Values.container.storageContainer }}
  AZURE_STORAGE_FOLDER: {{ quote .Values.container.storageFolder }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  ENDPOINT_ENABLED: {{ quote .Values.container.endpointEnabled }}
{{- end -}}
